import Head from "next/head";
import dynamic from "next/dynamic";

import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";
import Intro from "@/components/Intro/Intro";
import { Landing } from "@/components/Landing";
import { About } from "@/components/About";
import ProjectsWrapper from "@/components/ProjectsWrapper/ProjectsWrapper";
import { Footer } from "@/components/Footer";

// const Landing = dynamic(() => import("../components/Landing/Landing"));
// const About = dynamic(() => import("../components/About/About"));
// const ProjectsWrapper = dynamic(() =>
//   import("../components/ProjectsWrapper/ProjectsWrapper")
// );
// const Footer = dynamic(() => import("../components/Footer/Footer"));

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    (async () => {
      setTimeout(() => {
        setIsLoading(false);
        document.body.style.cursor = "default";
        window.scrollTo(0, 0);
      }, 2000);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Harshith G S</title>
        <meta name="description" content="Generated by Harshith" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoBg.ico" />
      </Head>
      <AnimatePresence mode="wait">{isLoading && <Intro />}</AnimatePresence>
      {!isLoading && (
        <>
          <Landing />
          <About />
          <ProjectsWrapper />
          <Footer />
        </>
      )}
    </>
  );
}
