import Head from "next/head";
import { About } from "@/components/About";
import ProjectsWrapper from "@/components/ProjectsWrapper/ProjectsWrapper";
import TransitionEffectVertical from "@/components/TransitionEffectVertical/TransitionEffectVertical";
import { Landing } from "@/components/Landing";
import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";
import Intro from "@/components/Intro/Intro";

export default function Home() {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    (async () => {
      setTimeout(() => {
        setIsLoading(false);
        document.body.style.cursor = "default";
        window.scrollTo(0, 0);
      }, 2000);
    })();
  }, []);

  return (
    <>
      <Head>
        <title>Harshith G S</title>
        <meta name="description" content="Generated by Harshith" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoBg.ico"/>
      </Head>
      <AnimatePresence mode="wait">{isLoading && <Intro />}</AnimatePresence>
      <TransitionEffectVertical />
      <Landing />
      <About />
      <ProjectsWrapper />
    </>
  );
}